# Generated by Django 4.1.2 on 2022-10-30 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('antisocial', '0001_initial'), ('antisocial', '0002_alter_post_supersedes')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('save_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated', to='antisocial.post')),
                ('tags', models.ManyToManyField(related_name='posts', to='antisocial.tag')),
            ],
        ),
    ]
